apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-api-demo
  namespace: default
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: insurance-api-container
          image: 692425240801.dkr.ecr.ap-south-1.amazonaws.com/smrinsuranceapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000