apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: PSFLEADMANAGEMENT-DEV-Cluster
  region: ap-south-1
nodeGroups:
  - name: PSFLEADMANAGEMENT-DEV-EKS-workers
    instanceType: t2.medium
    minSize: 1
    maxSize: 3
    
