apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: psfleadmanagement-dev-container
          image: 692425240801.dkr.ecr.ap-south-1.amazonaws.com/psfleadmanagement-dev:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
